# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e4781beec0e468e4fb52d9ad90a2adfd30f70d8fc8e49cb0db453578c3cc79208dcfac97ac2d27d5df9139a1d6f9f31a10d2ea2141626c3c8b8403b4442b02bc

test:
  secret_key_base: 2690bca9d0facdc1b2c2f1db75807d3972b4387b56e5e3e52f684b703e917bd53739b78944ca48c93e7192b399a3b47ecbf3ca603496ff7909c8c3b1fe0396fe

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
